{
 "title": "Bike Computer",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "measurement", "query": "cycle_activity" }
  ]
 },
 "panels": [
  {
   "title": "Total Distance",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"distance_cm\")*10 as mm FROM ${measurement} WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Mean Distance/hr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"distance_cm\")*10 as mm FROM ${measurement} WHERE $timeFilter GROUP BY time(1h)"
    }
   ]
  },
  {
   "title": "Total Revolutions",
   "type": "stat",
   "description": "Number of times the pedals have completed a full revolution.\n\nThis is probably broadly equivalent to taking a step",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"total_cycles\") as \"revolutions\" FROM ${measurement} WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Mean Revolutions/hr",
   "type": "stat",
   "description": "Number of times the pedals have completed a full revolution.\n\nThis is probably broadly equivalent to taking a step",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"total_cycles\") as \"revolutions\" FROM ${measurement} WHERE $timeFilter GROUP BY time(1h)"
    }
   ]
  },
  {
   "title": "Calories Burnt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"calories\") as \"calories\" FROM ${measurement} WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Mean Calories/hr",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"calories\") as \"calories\" FROM ${measurement} WHERE $timeFilter GROUP BY time(1h)"
    }
   ]
  },
  {
   "title": "Mean Speed",
   "type": "stat",
   "description": "Calculated average speed (excluding any periods of 0 speed)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"speed\") FROM ${measurement} WHERE $timeFilter and speed > 0"
    }
   ]
  },
  {
   "title": "Max Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"max_speed\") FROM ${measurement} WHERE $timeFilter "
    }
   ]
  },
  {
   "title": "Mean RPM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"rate\") FROM ${measurement} WHERE $timeFilter and rate > 0"
    }
   ]
  },
  {
   "title": "Revolutions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "SELECT sum(\"total_cycles\") as \"revolutions\" FROM ${measurement} WHERE $timeFilter GROUP BY time($interval), bike"
    }
   ]
  },
  {
   "title": "Calories Burnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "SELECT cumulative_sum(sum(\"calories\")) as \"calories\" FROM ${measurement} WHERE $timeFilter GROUP BY time($interval), bike"
    }
   ]
  },
  {
   "title": "Calories Burnt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "SELECT sum(\"calories\") as \"calories\" FROM ${measurement} WHERE $timeFilter GROUP BY time($interval), bike"
    }
   ]
  },
  {
   "title": "Cumulative Distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "SELECT cumulative_sum(sum(\"distance_cm\"))*10 FROM ${measurement} WHERE $timeFilter GROUP BY time($interval), bike"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "query": "SELECT mean(\"speed\") as \"mean\", max(\"max_speed\") as \"max\" FROM ${measurement} WHERE $timeFilter GROUP BY time($interval), bike, speed_format"
    }
   ]
  },
  {
   "title": "Revolutions Per Poll Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "SELECT mean(\"mean\") as \"mean\", max(\"max\") as \"max\", min(\"min\") as \"min\" FROM ${measurement} WHERE $timeFilter GROUP BY time($interval), bike, poll_interval"
    }
   ]
  },
  {
   "title": "Mean Revolutions/Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT mean(\"rate\") FROM ${measurement} WHERE $timeFilter GROUP BY time($interval), bike"
    }
   ]
  }
 ]
}